# Generated by Django 4.2.11 on 2024-04-17 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('google_maps_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cupid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.cupid')),
                ('dater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.dater')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointofinterest')),
            ],
        ),
    ]
